apiVersion: apps/v1
kind: Deployment
metadata:
  name: ntfy
  namespace: ntfy
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: ntfy
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ntfy
    spec:
      containers:
        - name: ntfy
          image: "binwiederhier/ntfy:v2.11.0@sha256:4a7d0f0adc6d5d9fc36e64ab55ef676e76e124a2bdd50ce115b6d9c1c7430294"
          args: ["serve"]
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
            requests:
              cpu: "10m"
              memory: "10Mi"
          ports:
            - containerPort: 80
              name: http
          volumeMounts:
            - name: config
              mountPath: "/etc/ntfy"
              readOnly: true
            - name: store
              mountPath: "/var/cache/ntfy"
          securityContext:
            readOnlyRootFilesystem: true
      volumes:
        - name: config
          configMap:
            name: ntfy
        - name: store
          emptyDir:
            sizeLimit: 500Mi
      securityContext:
        runAsUser: 1001
        runAsGroup: 1001
---
# Basic service for port 80
apiVersion: v1
kind: Service
metadata:
  name: ntfy
  namespace: ntfy
spec:
  selector:
    app.kubernetes.io/name: ntfy
  ports:
    - name: http
      port: 80
      targetPort: 80
