namespaceOverride: "prometheus"

prometheusOperator:
  tolerations:
    - key: "location"
      operator: "Equal"
      value: "external"
      effect: "NoSchedule"

prometheus:
  tolerations:
    - key: "location"
      operator: "Equal"
      value: "external"
      effect: "NoSchedule"
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: local-path
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi

grafana:
  namespaceOverride: "grafana"
  admin:
    existingSecret: "grafana"
    userKey: "admin-user"
    passwordKey: "admin-password"

alertmanager:
  extraSecretMounts:
    - name: alertmanager-file-config
      mountPath: /etc/alertmanager/config/secrets
      subpath: webhook
  config:
    receivers:
      - name: webhook
        webhookConfigs:
          - url_file: /etc/alertmanager/config/secrets/webhook
