apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: firefly-pvc
  namespace: firefly
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: smb
