config:
  env:
    DB_HOST: "db.tcp.postgres.postgres.svc.cluster.local"
    DB_CONNECTION: pgsql
    DB_PORT: "5432"
    DB_DATABASE: firefly
    DB_USERNAME: firefly
    DEFAULT_LANGUAGE: "en_US"
    DEFAULT_LOCALE: "equal"
    TZ: "Europe/ROME"
    TRUSTED_PROXIES: "**"
  existingSecret: "firefly-env"
persistence:
  enabled: true
  existingClaim: "firefly-pvc"
cronjob:
  enabled: true
  auth:
    existingSecret: "firefly-env"
    secretKey: "STATIC_CRON_TOKEN"
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
