apiVersion: apps/v1
kind: Deployment
metadata:
  name: pi-hole
  namespace: pi-hole
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: pi-hole
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pi-hole
    spec:
      tolerations:
        - key: location
          value: external
          effect: NoSchedule
      nodeSelector:
        kubernetes.io/hostname: kani
      containers:
        - name: pi-hole
          image: "pihole/pihole:latest@sha256:0def896a596e8d45780b6359dbf82fc8c75ef05b97e095452e67a0a4ccc95377"
          resources:
            limits:
              memory: "252Mi"
              cpu: "500m"
            requests:
              cpu: "10m"
              memory: "10Mi"
          env:
            - name: TZ
              value: "Europe/Rome"
            - name: PIHOLE_DNS_
              value: "1.1.1.1;1.0.0.1"
            - name: FTLCONF_LOCAL_IPV4
              value: "192.168.3.1"
            - name: VIRTUAL_HOST
              value: "pi-hole.k.joshuachp.dev"
          envFrom:
            - secretRef:
                name: pi-hole-env
                optional: false
          ports:
            - name: web
              protocol: TCP
              containerPort: 80
            - name: dns
              protocol: UDP
              containerPort: 53
            - name: dns-tcp
              protocol: TCP
              containerPort: 53
            - name: dhcp
              protocol: UDP
              containerPort: 67
          volumeMounts:
            - name: store
              mountPath: "/etc/dnsmasq.d/"
              subPath: "dnsmasq"
            - name: store
              mountPath: "/etc/pihole/"
              subPath: "pihole"
          securityContext:
            capabilities:
              add:
                - CAP_CHOWN
                - CAP_NET_ADMIN
                - CAP_NET_BIND_SERVICE
      volumes:
        - name: store
          persistentVolumeClaim:
            claimName: pi-hole-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: pi-hole
  namespace: pi-hole
spec:
  selector:
    app.kubernetes.io/name: pi-hole
  ports:
    - name: web
      port: 80
      protocol: TCP
      targetPort: 80
    - name: dns
      port: 53
      protocol: UDP
      targetPort: 53
    - name: dns-tcp
      port: 53
      protocol: TCP
      targetPort: 53
    - name: dhcp
      port: 67
      protocol: UDP
      targetPort: 67
---
apiVersion: v1
kind: Service
metadata:
  name: pi-hole-local
  namespace: pi-hole
  annotations:
    metallb.universe.tf/address-pool: external-pool
spec:
  selector:
    app.kubernetes.io/name: pi-hole
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: web
      port: 80
      protocol: TCP
      targetPort: 80
    - name: dns
      port: 53
      protocol: UDP
      targetPort: 53
    - name: dns-tcp
      port: 53
      protocol: TCP
      targetPort: 53
    - name: dhcp
      port: 67
      protocol: UDP
      targetPort: 67
  loadBalancerIP: 192.168.3.1
