apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pi-hole
  namespace: pi-hole
spec:
  ingressClassName: nginx
  rules:
    - host: pi-hole.k.joshuachp.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pi-hole
                port:
                  name: web
