apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pi-hole-pvc
  namespace: pi-hole
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path
