apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: renovate-ci-pvc
  namespace: woodpecker
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: local-path
