redis-cluster:
  enabled: true
  cluster:
    nodes: 1
postgresql:
  enabled: false
postgresql-ha:
  enabled: false

persistence:
  enabled: true
  create: false
  claimName: forgejo-pvc

signing:
  enabled: true
  existingSecret: forgejo-gpg-key

service:
  http:
    port: 3000
  ssh:
    port: 22

gitea:
  admin:
    existingSecret: forgejo-admin-secret
  config:
    server:
      DOMAIN: git.k.joshuachp.dev
      ROOT_URL: https://git.k.joshuachp.dev
      SSH_DOMAIN: git.k.joshuachp.dev
      SSH_PORT: 8022
    service:
      DISABLE_REGISTRATION: true
      REQUIRE_SIGNIN_VIEW: true
    database:
      DB_TYPE: postgres
      HOST: db.tcp.postgres.postgres.svc.cluster.local:5432
      NAME: forgejo
      USER: forgejo
    session:
      PROVIDER: db
    cache:
      ADAPTER: redis-cluster
    queue:
      TYPE: redis
      CONN_STR: redis+cluster://127.0.0.1:6379/0
    indexer:
      ISSUE_INDEXER_TYPE: bleve
      REPO_INDEXER_ENABLED: true
  additionalConfigSources:
    - secret:
        secretName: forgejo-app-ini-secret

extraVolumes:
  - name: indexers-volume
    ephemeral:
      volumeClaimTemplate:
        metadata:
          labels:
            type: forgejo-indexers-volume
        spec:
          accessModes:
            - ReadWriteOnce
          storageClassName: local-path
          resources:
            requests:
              storage: 500Mi
  - name: gpg-volume
    ephemeral:
      volumeClaimTemplate:
        metadata:
          labels:
            type: forgejo-gpg-volume
        spec:
          accessModes:
            - ReadWriteOnce
          storageClassName: local-path
          resources:
            requests:
              storage: 100Mi

extraVolumeMounts:
  - name: indexers-volume
    mountPath: /data/indexers
  - name: gpg-volume
    mountPath: /data/git/.gnupg

extraContainerVolumeMounts:
  - name: indexers-volume
    mountPath: /data/indexers
  - name: gpg-volume
    mountPath: /data/git/.gnupg

extraInitVolumeMounts:
  - name: indexers-volume
    mountPath: /data/indexers
  - name: gpg-volume
    mountPath: /data/git/.gnupg
