redis-cluster:
  enabled: false
postgresql:
  enabled: false
postgresql-ha:
  enabled: false

persistence:
  enabled: true
  create: false
  claimName: forgejo-pvc-local

signing:
  enabled: true
  existingSecret: forgejo-gpg-key
  gpgHome: /local/git/.gnupg

service:
  http:
    port: 3000
  ssh:
    port: 2222

gitea:
  admin:
    existingSecret: forgejo-admin-secret
  config:
    server:
      DOMAIN: git.k.joshuachp.dev
      ROOT_URL: https://git.k.joshuachp.dev
      SSH_DOMAIN: git.k.joshuachp.dev
      START_SSH_SERVER: true
      SSH_PORT: 22
      SSH_LISTEN_PORT: 2222
    service:
      DISABLE_REGISTRATION: true
      REQUIRE_SIGNIN_VIEW: true
      ENABLE_NOTIFY_MAIL: true
    database:
      DB_TYPE: postgres
      HOST: db.tcp.postgres.postgres.svc.cluster.local:5432
      NAME: forgejo
      USER: forgejo
    session:
      PROVIDER: db
    cache:
      ADAPTER: redis
      HOST: redis://:forgejo@tcp-redis.tcp.forgejo-redis-master.forgejo.svc.cluster.local:6379/0?pool_size=100&idle_timeout=180s
    queue:
      TYPE: redis
      CONN_STR: redis://:forgejo@tcp-redis.tcp.forgejo-redis-master.forgejo.svc.cluster.local:6379/0?pool_size=100&idle_timeout=180s
    indexer:
      ISSUE_INDEXER_TYPE: bleve
      REPO_INDEXER_ENABLED: true
    webhook:
      ALLOWED_HOST_LIST: private,external
  additionalConfigSources:
    - secret:
        secretName: forgejo-app-ini-secret

extraVolumes:
  - name: local-volume
    emptyDir:
      sizeLimit: 500Mi
  - name: forgejo-pvc
    persistentVolumeClaim:
      claimName: forgejo-pvc

extraVolumeMounts:
  - name: local-volume
    mountPath: /local/git
    subPath: git
  - name: local-volume
    mountPath: /data/tmp
    subPath: tmp
  - name: local-volume
    mountPath: /data/indexers
    subPath: indexers
  - name: forgejo-pvc
    mountPath: /other

extraContainerVolumeMounts:
  - name: local-volume
    mountPath: /local/git
    subPath: git
  - name: local-volume
    mountPath: /data/tmp
    subPath: tmp
  - name: local-volume
    mountPath: /data/indexers
    subPath: indexers
  - name: forgejo-pvc
    mountPath: /other

extraInitVolumeMounts:
  - name: local-volume
    mountPath: /local/git
    subPath: git
  - name: local-volume
    mountPath: /data/tmp
    subPath: tmp
  - name: local-volume
    mountPath: /data/indexers
    subPath: indexers
  - name: forgejo-pvc
    mountPath: /other
