apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  custom.override: |
    rewrite continue name git.k.joshuachp.dev traefik.traefik.svc.cluster.local
    rewrite continue name traefik.k.joshuachp.dev traefik.traefik.svc.cluster.local
