apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: k-joshuachp-dev-staging
  namespace: traefik
spec:
  secretName: cert-k-joshuachp-dev-staging
  commonName: "k.joshuachp.dev"
  dnsNames:
    - "k.joshuachp.dev"
    - "*.k.joshuachp.dev"
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
