# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  # Use the systemd-boot EFI boot loader.
  boot = {
    loader = {
      systemd-boot.enable = true;
      efi.canTouchEfiVariables = true;
      efi.efiSysMountPoint = "/efi";
    };

    initrd = {
      availableKernelModules = [
        "vmd"
        "xhci_pci"
        "ahci"
        "nvme"
        "usbhid"
        "usb_storage"
        "sd_mod"
        "rtsx_pci_sdmmc"
      ];
      kernelModules = [ "dm-snapshot" ];
    };
    kernelModules = [ "kvm-intel" ];
    extraModulePackages = [ ];
  };

  fileSystems = {
    "/efi" = {
      device = "/dev/disk/by-uuid/F33C-09F7";
      fsType = "vfat";
      options = [ "umask=0077" ];
    };

    "/" = {
      device = "/dev/Linux/root";
      fsType = "btrfs";
      options = [
        "defaults"
        "subvol=root"
        "compress=zstd"
        "noatime"
      ];
    };

    "/home" = {
      device = "/dev/Linux/root";
      fsType = "btrfs";
      options = [
        "defaults"
        "subvol=home"
        "compress=zstd"
      ];
    };

    "/nix" = {
      device = "/dev/Linux/root";
      fsType = "btrfs";
      options = [
        "defaults"
        "subvol=nix"
        "compress=zstd"
        "noatime"
      ];
    };

    "/var" = {
      device = "/dev/Linux/root";
      fsType = "btrfs";
      options = [
        "defaults"
        "subvol=var"
        "compress=zstd"
      ];
    };
  };

  swapDevices = [ { device = "/dev/Linux/swap"; } ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  powerManagement.cpuFreqGovernor = lib.mkDefault "performance";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
