controller:
  service:
    annotations:
      # TODO: replace
      metallb.universe.tf/loadBalancerIPs: 10.2.0.1
    loadBalancerSourceRanges:
      - 127.0.0.1/32
      - 10.0.0.0/16
      - 10.1.0.0/16
  extraArgs:
    default-ssl-certificate: traefik/cert-k-joshuachp-dev
  config:
    hsts: true
    hsts-preload: true
    enable-brotli: true
    use-http2: true

tcp:
  "22": "forgejo/forgejo-ssh:2222"
  "5432": "postgres/postgres:5432"
  "22000": "syncthing/syncthing-service:22000"
udp:
  "22000": "syncthing/syncthing-service:22000"
  "21027": "syncthing/syncthing-service:21027"
