apiVersion: apps/v1
kind: Deployment
metadata:
  name: miniflux
  namespace: miniflux
  labels:
    app.kubernetes.io/name: miniflux
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: miniflux
  template:
    metadata:
      namespace: miniflux
      labels:
        app.kubernetes.io/name: miniflux
    spec:
      containers:
        - image: miniflux/miniflux:2.2.6@sha256:df4f27349b7eb8eb424cfa5c1f42e597dc81f7aa44fba0fd769a5db922dfde49
          name: miniflux
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: RUN_MIGRATIONS
              value: "1"
            - name: CREATE_ADMIN
              value: "1"
            - name: BASE_URL
              value: "https://miniflux.k.joshuachp.dev"
          envFrom:
            - secretRef:
                name: miniflux-env
                optional: false
          resources:
            limits:
              memory: "256Mi"
              cpu: "100m"
            requests:
              cpu: "50m"
              memory: "100Mi"
          securityContext:
            readOnlyRootFilesystem: true
          livenessProbe:
            exec:
              command:
                - "/bin/sh"
                - "-c"
                - "miniflux -healthcheck auto"
          readinessProbe:
            exec:
              command:
                - "/bin/sh"
                - "-c"
                - "miniflux -healthcheck auto"
      securityContext:
        runAsUser: 65534
        runAsGroup: 65534
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: miniflux
  name: miniflux
  namespace: miniflux
spec:
  selector:
    app.kubernetes.io/name: miniflux
  ports:
    - name: http
      port: 8080
