agent:
  env:
    WOODPECKER_BACKEND_K8S_STORAGE_CLASS: "local-path"
  extraSecretNamesForEnvFrom:
    - woodpecker-env
server:
  env:
    WOODPECKER_GITEA: true
    WOODPECKER_HOST: https://ci.k.joshuachp.dev
    WOODPECKER_GITEA_URL: http://http.tcp.forgejo-http.forgejo.svc.cluster.local
  extraSecretNamesForEnvFrom:
    - woodpecker-env
  persistentVolume:
    storageClass: smb
