agent:
  replicaCount: 1
  env:
    WOODPECKER_BACKEND_K8S_STORAGE_CLASS: "local-path"
    WOODPECKER_BACKEND_K8S_STORAGE_RWX: false
  extraSecretNamesForEnvFrom:
    - woodpecker-env
  persistentVolume:
    storageClass: local-path
  tolerations:
    - key: "location"
      operator: "Equal"
      value: "external"
      effect: "NoSchedule"
server:
  env:
    WOODPECKER_ADMIN: woodpecker,admin,joshuachp
    WOODPECKER_GITEA: true
    WOODPECKER_GITEA_URL: https://git.k.joshuachp.dev
    WOODPECKER_HOST: https://ci.k.joshuachp.dev
    WOODPECKER_WEBHOOK_HOST: http://woodpecker-server.woodpecker.svc.cluster.local
    WOODPECKER_AUTHENTICATE_PUBLIC_REPOS: true
  extraSecretNamesForEnvFrom:
    - woodpecker-env
    - woodpecker-server-env
  persistentVolume:
    storageClass: smb
