agent:
  replicaCount: 1
  env:
    WOODPECKER_BACKEND_K8S_STORAGE_CLASS: "local-path"
    WOODPECKER_BACKEND_K8S_STORAGE_RWX: false
    WOODPECKER_MAX_WORKFLOWS: "2"
  extraSecretNamesForEnvFrom:
    - woodpecker-env
  persistentVolume:
    storageClass: local-path
  tolerations:
    - key: "location"
      operator: "Equal"
      value: "external"
      effect: "NoSchedule"
server:
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - host: ci.k.joshuachp.dev
  env:
    WOODPECKER_ADMIN: woodpecker,admin,joshuachp
    WOODPECKER_GITEA: true
    WOODPECKER_GITEA_URL: https://git.k.joshuachp.dev
    WOODPECKER_HOST: https://ci.k.joshuachp.dev
    WOODPECKER_WEBHOOK_HOST: http://woodpecker-server.woodpecker.svc.cluster.local
    WOODPECKER_AUTHENTICATE_PUBLIC_REPOS: true
    WOODPECKER_LIMIT_MEM: "2147483648" # 2GB
    WOODPECKER_LIMIT_MEM_SWAP: "2147483648" # 2GB
    WOODPECKER_LIMIT_CPU_SET: "1,2"
  extraSecretNamesForEnvFrom:
    - woodpecker-env
    - woodpecker-server-env
  persistentVolume:
    storageClass: local-path
