agent:
  env:
    WOODPECKER_BACKEND_K8S_STORAGE_CLASS: "local-path"
  extraSecretNamesForEnvFrom:
    - woodpecker-env
server:
  env:
    WOODPECKER_ADMIN: woodpecker,admin,joshuachp
    WOODPECKER_GITEA: true
    WOODPECKER_GITEA_URL: https://git.k.joshuachp.dev
    WOODPECKER_HOST: https://ci.k.joshuachp.dev
  extraSecretNamesForEnvFrom:
    - woodpecker-env
  persistentVolume:
    storageClass: smb
