apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-external
  namespace: traefik
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - match: "Host(`traefik.k.joshuachp.dev`)"
      kind: Rule
      services:
        - name: api@internal
          kind: TraefikService
  tls:
    domains:
      - main: k.joshuachp.dev
        sans:
          - "*.k.joshuachp.dev"
