apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-db
  namespace: nextcloud
spec:
  # 12h jobs should is probably stuck
  concurrencyPolicy: Replace
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  schedule: "0 */12 * * *"
  jobTemplate:
    metadata:
      name: backup-db
      namespace: nextcloud
    spec:
      ttlSecondsAfterFinished: 259200
      template:
        metadata:
          namespace: nextcloud
        spec:
          tolerations:
            - key: "location"
              operator: "Equal"
              value: "external"
              effect: "NoSchedule"
          containers:
            - name: backup-db
              image: joshuachp/restic-pg:0.1.0@sha256:1e58ef216279d94d03a208f2d9b73199e53232208d9b8eea55042d3433c1c3ee
              envFrom:
                - secretRef:
                    name: nextcloud-backup-db
              env:
                - name: RESTIC_CACHE_DIR
                  value: /tmp/restic
                - name: RESTIC_HOST
                  value: backup-db
              volumeMounts:
                - name: ssh-config
                  mountPath: /etc/ssh/ssh_config.d/restic.conf
                  subPath: config
                  readOnly: true
                - name: ssh-config
                  mountPath: /etc/ssh/ssh_known_hosts
                  subPath: knownHosts
                  readOnly: true
                - name: ssh-config
                  mountPath: /etc/ssh/restic-key
                  subPath: privateKey
                  readOnly: true
                  mode:
                - name: store
                  mountPath: /tmp
                  subPath: tmp
              securityContext:
                readOnlyRootFilesystem: true
              command:
                - "/bin/sh"
                - "-c"
                - |
                  set -uex
                  restic --verbose backup --skip-if-unchanged --stdin-from-command -- pg_dumpall -w
          restartPolicy: OnFailure
          volumes:
            - name: ssh-config
              secret:
                secretName: restic-ssh-key
                defaultMode: 0400
                items:
                  - key: config
                    path: config
                  - key: knownHosts
                    path: knownHosts
                  - key: privateKey
                    path: privateKey
            - name: store
              emptyDir:
                sizeLimit: 500Mi
          securityContext:
            runAsUser: 0
            runAsGroup: 0
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-db-maintenance
  namespace: nextcloud
spec:
  # 12h jobs should is probably stuck
  concurrencyPolicy: Replace
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  schedule: "0 4 * * *"
  jobTemplate:
    metadata:
      name: backup-db-maintenance
      namespace: nextcloud
    spec:
      ttlSecondsAfterFinished: 259200
      template:
        metadata:
          namespace: nextcloud
        spec:
          containers:
            - name: backup-db-maintenance
              image: joshuachp/restic:0.1.2@sha256:a0a278c605157b7ce2b6f1574d73f47c892cb652aa3b7918a415773be3b52594
              envFrom:
                - secretRef:
                    name: nextcloud-backup-db
              env:
                - name: RESTIC_CACHE_DIR
                  value: /tmp/restic
              volumeMounts:
                - name: ssh-config
                  mountPath: /etc/ssh/ssh_config.d/restic.conf
                  subPath: config
                  readOnly: true
                - name: ssh-config
                  mountPath: /etc/ssh/ssh_known_hosts
                  subPath: knownHosts
                  readOnly: true
                - name: ssh-config
                  mountPath: /etc/ssh/restic-key
                  subPath: privateKey
                  readOnly: true
                  mode:
                - name: store
                  mountPath: /tmp
                  subPath: tmp
              securityContext:
                readOnlyRootFilesystem: true
              command:
                - "/bin/sh"
                - "-c"
                - |
                  set -uex
                  restic forget --keep-daily 7 --keep-weekly 3 --keep-within 1d --prune &&
                    restic check --read-data-subset=1/10
          restartPolicy: OnFailure
          volumes:
            - name: ssh-config
              secret:
                secretName: restic-ssh-key
                defaultMode: 0400
                items:
                  - key: config
                    path: config
                  - key: knownHosts
                    path: knownHosts
                  - key: privateKey
                    path: privateKey
            - name: store
              emptyDir:
                sizeLimit: 500Mi
          securityContext:
            runAsUser: 0
            runAsGroup: 0
