ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/affinity: cookie
    # .htaccess redirect
    nginx.ingress.kubernetes.io/proxy-redirect-from: "http://nextcloud.k.joshuachp.dev/"
    nginx.ingress.kubernetes.io/proxy-redirect-to: "https://nextcloud.k.joshuachp.dev/"

phpClientHttpsFix:
  enabled: true

tolerations:
  - key: "location"
    operator: "Equal"
    value: "external"
    effect: "NoSchedule"

nextcloud:
  host: nextcloud.k.joshuachp.dev
  defaultConfigs:
    imaginary.config.php: true
  existingSecret:
    enabled: true
    secretName: nextcloud-secret
  mail:
    enabled: true
    # the user we send email as
    fromAddress: noreplay
    domain: k.joshuachp.dev
  configs:
    main.config.php: |
      <?php
      $CONFIG = array (
        'maintenance_window_start' => 1,
        'default_phone_region' => 'IT',
        'overwrite.cli.url' => 'https://nextcloud.k.joshuachp.dev',
      );
    proxy.config.php: |-
      <?php
      $CONFIG = array (
        'trusted_domains' => array(
          0 => 'localhost',
          1 => 'nextcloud.k.joshuachp.dev',
        ),
        'trusted_proxies' => array(
          0 => '127.0.0.1',
          1 => '10.0.0.0/8',
        ),
        'forwarded_for_headers' => array('HTTP_X_FORWARDED_FOR'),
      );
  phpConfigs:
    zz-opcache-setup.ini: |-
      opcache.enable_cli = 1
      opcache.revalidate_freq = 60
      opcache.jit = 1255
      opcache.jit_buffer_size = 8M

imaginary:
  enabled: true

internalDatabase:
  enabled: false

persistence:
  enabled: true
  storageClass: local-path
  existingClaim: nextcloud-pvc
  nextcloudData:
    enabled: true
    existingClaim: nextcloud-data-pvc

redis:
  enabled: true
  architecture: standalone
  global:
    storageClass: local-path
  auth:
    enabled: false
  networkPolicy:
    enabled: true
  master:
    resourcesPreset: nano
    persistence:
      existingClaim: nextcloud-redis-pvc
    tolerations:
      - key: "location"
        operator: "Equal"
        value: "external"
        effect: "NoSchedule"

cronjob:
  enabled: true

externalDatabase:
  enabled: true
  type: postgresql
  existingSecret:
    enabled: true
    secretName: nextcloud-secret
    hostKey: db-host
    databaseKey: db-name
    usernameKey: db-username
    passwordKey: db-password

postgresql:
  enabled: true
  architecture: standalone
  global:
    storageClass: local-path
  auth:
    database: nextcloud
    username: nextcloud
    existingSecret: nextcloud-postgres
  primary:
    resourcesPreset: nano
    tolerations:
      - key: "location"
        operator: "Equal"
        value: "external"
        effect: "NoSchedule"
    persistence:
      enabled: true
      existingClaim: nextcloud-postgres-pvc
