ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/affinity: cookie
    # .htaccess redirect
    nginx.ingress.kubernetes.io/proxy-redirect-from: "http://nextcloud.k.joshuachp.dev/"
    nginx.ingress.kubernetes.io/proxy-redirect-to: "https://nextcloud.k.joshuachp.dev/"
    # Upload size
    nginx.ingress.kubernetes.io/proxy-body-size: 512m

phpClientHttpsFix:
  enabled: true

tolerations:
  - key: "location"
    operator: "Equal"
    value: "external"
    effect: "NoSchedule"

nextcloud:
  host: nextcloud.k.joshuachp.dev
  defaultConfigs:
    imaginary.config.php: true
  existingSecret:
    enabled: true
    secretName: nextcloud-secret
  mail:
    enabled: true
    # the user we send email as
    fromAddress: noreplay
    domain: k.joshuachp.dev
  configs:
    zz-user.config.php: |
      <?php
      $CONFIG = [
        'maintenance_window_start' => 1,
        'default_phone_region' => 'IT',
        'overwrite.cli.url' => 'https://nextcloud.k.joshuachp.dev',
        'trusted_domains' => [
          'localhost',
          'nextcloud.k.joshuachp.dev',
        ],
        'trusted_proxies' => [
          '127.0.0.1',
          '10.0.0.0/8',
        ],
        'forwarded_for_headers' => ['HTTP_X_FORWARDED_FOR'],
        'enabledPreviewProviders' => [
          'OC\Preview\Imaginary',
          'OC\Preview\ImaginaryPDF',
          'OC\Preview\Movie',
          /*
            defaults:
            https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/config_sample_php_parameters.html#enabledpreviewproviders
          */
          'OC\Preview\BMP',
          // 'OC\Preview\GIF',
          // 'OC\Preview\JPEG',
          'OC\Preview\Krita',
          'OC\Preview\MarkDown',
          'OC\Preview\MP3',
          'OC\Preview\OpenDocument',
          // 'OC\Preview\PNG',
          'OC\Preview\TXT',
          'OC\Preview\XBitmap',
        ],
      ];
  phpConfigs:
    zz-opcache-setup.ini: |-
      opcache.enable_cli = 1
      opcache.revalidate_freq = 60
      opcache.jit = 1255
      opcache.jit_buffer_size = 8M

lifecycle:
  postStartCommand:
    [
      "/bin/sh",
      "-c",
      "apt-get update -y && apt-get install ffmpeg -y --no-install-recommends",
    ]

imaginary:
  enabled: true

internalDatabase:
  enabled: false

persistence:
  enabled: true
  storageClass: local-path
  existingClaim: nextcloud-pvc
  nextcloudData:
    enabled: true
    existingClaim: nextcloud-data-pvc

redis:
  enabled: true
  architecture: standalone
  global:
    storageClass: local-path
  auth:
    enabled: false
  networkPolicy:
    enabled: true
  master:
    resourcesPreset: small
    persistence:
      existingClaim: nextcloud-redis-pvc
    tolerations:
      - key: "location"
        operator: "Equal"
        value: "external"
        effect: "NoSchedule"

cronjob:
  enabled: true

externalDatabase:
  enabled: true
  type: postgresql
  existingSecret:
    enabled: true
    secretName: nextcloud-secret
    hostKey: db-host
    databaseKey: db-name
    usernameKey: db-username
    passwordKey: db-password

postgresql:
  enabled: true
  architecture: standalone
  global:
    storageClass: local-path
  auth:
    database: nextcloud
    username: nextcloud
    existingSecret: nextcloud-postgres
  primary:
    resourcesPreset: small
    tolerations:
      - key: "location"
        operator: "Equal"
        value: "external"
        effect: "NoSchedule"
    persistence:
      enabled: true
      existingClaim: nextcloud-postgres-pvc
