ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/affinity: cookie

tolerations:
  - key: "location"
    operator: "Equal"
    value: "external"
    effect: "NoSchedule"

nextcloud:
  host: nextcloud.k.joshuachp.dev
  existingSecret:
    enabled: true
    secretName: nextcloud-secret
  mail:
    enabled: true
    # the user we send email as
    fromAddress: Nextcloud <noreplay@k.joshuachp.dev>

internalDatabase:
  enabled: false

persistence:
  enabled: true
  existingClaim: nextcloud-pvc
  nextcloudData:
    enabled: true
    existingClaim: nextcloud-data-pvc

redis:
  enabled: true
  tolerations:
    - key: "location"
      operator: "Equal"
      value: "external"
      effect: "NoSchedule"

cronjob:
  enabled: true

externalDatabase:
  enabled: true
  type: postgresql

postgresql:
  enabled: true
  tolerations:
    - key: "location"
      operator: "Equal"
      value: "external"
      effect: "NoSchedule"
  primary:
    persistence:
      enabled: true
      existingClaim: nextcloud-postgres-pvc
