globalArguments:
  - "--global.checknewversion=false"
  - "--global.sendanonymoususage=false"

ports:
  web:
    redirectTo:
      port: websecure
  websecure:
    tls:
      enabled: true
  ssh:
    port: 22
    exposedPort: 22
    protocol: TCP
    expose:
      default: true
      internal: false
  syncthing-tcp:
    port: 22000
    exposedPort: 22000
    protocol: TCP
    expose:
      default: true
      internal: false
  syncthing-quic:
    port: 22000
    exposedPort: 22000
    protocol: UDP
    expose:
      default: true
      internal: false
  syncthing-disc:
    port: 21027
    exposedPort: 21027
    protocol: UDP
    expose:
      default: true
      internal: false
  db:
    port: 5432
    exposedPort: 5432
    protocol: TCP
    expose:
      default: true
      internal: false

providers:
  kubernetesCRD:
    enabled: true
  kubernetesIngress:
    enabled: true

rbac:
  enabled: true

logs:
  general:
    level: INFO
    format: json
  # access:
  #   enabled: true
  #   format: json
  #   fields:
  #     headers:
  #       defaultmode: keep

service:
  annotations:
    metallb.universe.tf/loadBalancerIPs: 10.2.0.2
  loadBalancerSourceRanges:
    - 127.0.0.1/32
    - 10.0.0.0/16
    - 10.1.0.0/16
