globalArguments:
  - "--global.checknewversion=false"
  - "--global.sendanonymoususage=false"

additionalArguments:
  - "--serversTransport.insecureSkipVerify=true"

deployment:
  kind: "DaemonSet"

ports:
  web:
    redirectTo:
      port: websecure
  websecure:
    tls:
      enabled: true
  ssh:
    port: 8022
    expose: true
    exposedPort: 8022
    protocol: TCP
    exposeInternal: false
  syncthing-tcp:
    port: 22000
    expose: true
    exposedPort: 22000
    protocol: TCP
    exposeInternal: false
  syncthing-quic:
    port: 22000
    expose: true
    exposedPort: 22000
    protocol: UDP
    exposeInternal: false
  syncthing-disc:
    port: 21027
    expose: true
    exposedPort: 21027
    protocol: UDP
    exposeInternal: false

providers:
  kubernetesCRD:
    enabled: true
    allowExternalNameServices: true
    allowCrossNamespace: true
  kubernetesIngress:
    enabled: true
    allowExternalNameServices: true

rbac:
  enabled: true

logs:
  general:
    level: DEBUG
    format: json
  access:
    enabled: true
    format: json
    fields:
      headers:
        defaultmode: keep

service:
  loadBalancerSourceRanges:
    - 127.0.0.1/32
    - 10.0.0.1/20
