# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  lib,
  pkgs,
  modulesPath,
  system,
  ...
}:
{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];
  config = {
    # Use the systemd-boot EFI boot loader.
    boot = {
      loader = {
        systemd-boot.enable = true;
        efi = {
          canTouchEfiVariables = true;
          efiSysMountPoint = "/efi";
        };
      };
      kernelPackages = pkgs.linuxPackages_6_9;
      initrd = {
        availableKernelModules = [
          "xhci_pci"
          "nvme"
          "ahci"
          "usbhid"
          "sd_mod"
          "usb_storage"
        ];
        kernelModules = [
          "dm-snapshot"
          "amdgpu"
        ];
      };
      kernelModules = [ "kvm-amd" ];
      extraModulePackages = [ ];
      # extraModprobeConfig = ''
      #   options snd-hda-intel model=alc285-hp-amp-init
      # '';
    };

    fileSystems = {
      "/" = {
        device = "/dev/Linux/root";
        fsType = "btrfs";
        options = [
          "defaults"
          "subvol=root"
          "compress=zstd"
          "noatime"
        ];
      };

      "/nix" = {
        device = "/dev/Linux/root";
        fsType = "btrfs";
        options = [
          "defaults"
          "subvol=nix"
          "compress=zstd"
          "noatime"
        ];
      };

      "/efi" = {
        device = "/dev/disk/by-uuid/7D9B-B214";
        fsType = "vfat";
        options = [ "umask=0077" ];
      };

      "/boot" = {
        device = "/dev/disk/by-uuid/0f114536-503f-45ea-bf38-c866320bda2c";
        fsType = "ext4";
      };

      "/home" = {
        device = "/dev/Linux/root";
        fsType = "btrfs";
        options = [
          "defaults"
          "subvol=home"
          "compress=zstd"
          "noatime"
        ];
      };

      "/home/joshuachp/share" = {
        device = "/dev/Linux/share";
        fsType = "btrfs";
        options = [
          "defaults"
          "user"
          "exec"
          "compress=zstd"
          "noatime"
        ];
      };

      "/var" = {
        device = "/dev/Linux/root";
        fsType = "btrfs";
        options = [
          "defaults"
          "subvol=var"
          "compress=zstd"
          "noatime"
        ];
      };
    };

    swapDevices = [ { device = "/dev/Linux/swap"; } ];

    nixpkgs.hostPlatform = lib.mkDefault system;
    hardware = {
      enableRedistributableFirmware = true;
      cpu.amd.updateMicrocode = true;
    };
  };
}
