when:
  branch: main
  event:
    - push
    - pull_request
    - manual
steps:
  - name: flake check
    image: joshuachp/nixos:0.1.4@sha256:160bc1590fbd31d0a76293b453b35d6a0169b84b3163e11085c9dcf81eeddcc8
    environment:
      NIX_CONFIG:
        from_secret: NIX_CONFIG
    secrets: [BUILDERS, BUILDER_KEY, BUILDER_HOST_KEYS]
    commands:
      - /setup-remote.sh
      - nix flake check
