when:
  branch: main
  event:
    - push
    - pull_request
    - manual
steps:
  - name: check
    image: joshuachp/nixos:0.1.6@sha256:1dece1824ba1b3992eea854ad05e590204cdbeba0db11c8e5b2d34ad03d184c6
    environment:
      NIX_CONFIG:
        from_secret: NIX_CONFIG
      BUILDERS:
        from_secret: BUILDERS
      BUILDER_KEY:
        from_secret: BUILDER_KEY
      BUILDER_HOST_KEYS:
        from_secret: BUILDER_HOST_KEYS
      GC_MAXIMUM_HEAP_SIZE: 5G
    backend_options:
      kubernetes:
        resources:
          requests:
            memory: 200Mi
            cpu: 100m
          limits:
            memory: 5120Mi
            cpu: 1000m
    commands:
      - /setup-remote.sh
      # TODO: cache the pre-commit repos
      - |
        nix develop -c pre-commit -- \
          run --show-diff-on-failure --color=always --all-files
