when:
  branch: main
  event:
    - push
    - pull_request
    - manual
steps:
  - name: flake check
    image: joshuachp/nixos:0.1.6@sha256:34a7bd794e6ec1ce91f4a32a35dde2514b91a4f173ae31bb9ecc284b8b875a2f
    environment:
      NIX_CONFIG:
        from_secret: NIX_CONFIG
      BUILDERS:
        from_secret: BUILDERS
      BUILDER_KEY:
        from_secret: BUILDER_KEY
      BUILDER_HOST_KEYS:
        from_secret: BUILDER_HOST_KEYS
      GC_MAXIMUM_HEAP_SIZE: 5G
    backend_options:
      kubernetes:
        resources:
          requests:
            memory: 200Mi
            cpu: 100m
          limits:
            memory: 5120Mi
            cpu: 1000m
    commands:
      - /setup-remote.sh
      # TODO: cache the pre-commit repos
      - |
        nix develop -c pre-commit -- run --from-ref "$CI_COMMIT_TARGET_BRANCH" \
          --to-ref "$CI_COMMIT_SOURCE_BRANCH"
