when:
  branch: main
  event:
    - push
    - pull_request
    - manual
steps:
  - name: flake check
    image: joshuachp/nixos:0.1.6@sha256:42b4a2524311c2d134fe472e26516a81943fe90ec736c01263910f67a718264b
    environment:
      NIX_CONFIG:
        from_secret: NIX_CONFIG
      BUILDERS:
        from_secret: BUILDERS
      BUILDER_KEY:
        from_secret: BUILDER_KEY
      BUILDER_HOST_KEYS:
        from_secret: BUILDER_HOST_KEYS
      GC_MAXIMUM_HEAP_SIZE: 7G
    backend_options:
      kubernetes:
        resources:
          requests:
            memory: 200Mi
            cpu: 100m
          limits:
            memory: 5120Mi
            cpu: 1000m
    commands:
      - /setup-remote.sh
      - nix flake check
