when:
  branch: main
  event:
    - push
    - pull_request
steps:
  - name: flake check
    image: joshuachp/nixos:0.1.2
    environment:
      NIX_CONFIG:
        from_secret: NIX_CONFIG
    secrets: [BUILDERS, BUILDER_KEY]
    commands:
      - mkdir -p ~/.ssh
      - echo "$BUILDER_KEY" > ~/.ssh/id_ed25519
      - chmod -R 600 ~/.ssh
      - nix flake check --builders "$BUILDERS"
