when:
  branch: main
  event:
    - push
    - pull_request
steps:
  - name: flake check
    image: joshuachp/nixos:0.1.1
    environment:
      NIX_CONFIG:
        from_secret: NIX_CONFIG
    commands:
      - git config --global --replace-all safe.directory /woodpecker/src/git.k.joshuachp.dev/joshuachp/nixos-config
      - nix flake check
