when:
  branch: main
  event:
    - push
    - pull_request
    - manual
steps:
  - name: flake check
    image: joshuachp/nixos:0.1.5@sha256:294bfbe75986862321af7ed6cb8e6c8f1ebc43eb882ac39a10249f3a7ccf9aee
    environment:
      NIX_CONFIG:
        from_secret: NIX_CONFIG
      BUILDERS:
        from_secret: BUILDERS
      BUILDER_KEY:
        from_secret: BUILDER_KEY
      BUILDER_HOST_KEYS:
        from_secret: BUILDER_HOST_KEYS
      GC_MAXIMUM_HEAP_SIZE: 7G
    backend_options:
      kubernetes:
        resources:
          requests:
            memory: 200Mi
            cpu: 100m
          limits:
            memory: 5120Mi
            cpu: 1000m
    commands:
      - /setup-remote.sh
      - nix flake check
