when:
  branch: main
  event:
    - push
    - pull_request
    - manual
steps:
  - name: flake check
    image: joshuachp/nixos:0.1.3@sha256:b272184318be604cd874d441e06268352d25d87597133ecf573a3630dea3f1cf
    environment:
      NIX_CONFIG:
        from_secret: NIX_CONFIG
    secrets: [BUILDERS, BUILDER_KEY, BUILDER_HOST_KEYS]
    commands:
      - /setup-remote.sh
      - nix flake check
