# Run renovate on push to main
when:
  branch: main
  event:
    - push
    - manual
skip_clone: true
steps:
  - name: renovate
    image: renovate/renovate:38.124.3@sha256:ae2a397fb02df22a48f6757d6b79bf0b76bac2020a910ec60c792dc59dafcf45
    secrets:
      [
        GITHUB_COM_TOKEN,
        RENOVATE_ENDPOINT,
        RENOVATE_GIT_AUTHOR,
        RENOVATE_USERNAME,
        RENOVATE_TOKEN,
        RENOVATE_GIT_PRIVATE_KEY,
      ]
    environment:
      RENOVATE_CONFIG_FILE: /tmp/config.json
      RENOVATE_PLATFORM: gitea
    commands:
      - |
        echo '{
          "repositories": ["joshuachp/nixos-config"],
          "extends":["config:recommended"],
          "dependencyDashboard": true
        }' > /tmp/config.json
      - renovate
