# Run renovate on push to main
when:
  branch: main
  event:
    - push
    - manual
skip_clone: true
steps:
  - name: renovate
    image: renovate/renovate:39.113.0@sha256:766ec1382151e12893e2965e17a1f67c094eb1b0c90c4b9d6ff134a0161f56f3
    # TODO: Add when non root containers work in woodpacker
    # volumes:
    #   - renovate-ci-pvc:/renovate-cache
    environment:
      RENOVATE_CONFIG_FILE: /tmp/config.json
      # RENOVATE_CACHE_DIR: /renovate-cache
      RENOVATE_PLATFORM: gitea
      GITHUB_COM_TOKEN:
        from_secret: GITHUB_COM_TOKEN
      RENOVATE_ENDPOINT:
        from_secret: RENOVATE_ENDPOINT
      RENOVATE_GIT_AUTHOR:
        from_secret: RENOVATE_GIT_AUTHOR
      RENOVATE_USERNAME:
        from_secret: RENOVATE_USERNAME
      RENOVATE_TOKEN:
        from_secret: RENOVATE_TOKEN
      RENOVATE_GIT_PRIVATE_KEY:
        from_secret: RENOVATE_GIT_PRIVATE_KEY
    backend_options:
      kubernetes:
        securityContext:
          runAsUser: 0
          runAsGroup: 0
          fsGroup: 0
          privileged: true
    commands:
      - |
        printf '{
          "repositories": ["%s"],
          "extends":["config:recommended"],
          "dependencyDashboard": true
        }' "$CI_REPO" > /tmp/config.json
      - renovate
