# Run renovate on push to main
when:
  branch: main
  event:
    - push
    - manual
skip_clone: true
steps:
  - name: renovate
    image: renovate/renovate:38.116.0@sha256:ec114d970032e22b980628292c421c0b2e5410310400a6d9b572836f7874b778
    secrets:
      [
        GITHUB_COM_TOKEN,
        RENOVATE_ENDPOINT,
        RENOVATE_GIT_AUTHOR,
        RENOVATE_USERNAME,
        RENOVATE_TOKEN,
        RENOVATE_GIT_PRIVATE_KEY,
      ]
    environment:
      RENOVATE_CONFIG_FILE: /tmp/config.json
      RENOVATE_PLATFORM: gitea
    commands:
      - |
        echo '{
          "repositories": ["joshuachp/nixos-config"],
          "extends":["config:recommended"],
          "dependencyDashboard": true
        }' > /tmp/config.json
      - renovate
