# Run renovate on push to main
when:
  branch: main
  event:
    - push
    - manual
skip_clone: true
steps:
  - name: renovate
    image: renovate/renovate:38.110.5@sha256:de3a93645184b7c2e4dc1c0a4d9326ef32ba5c04f0a85b165b65cf28216a235d
    secrets:
      [
        GITHUB_COM_TOKEN,
        RENOVATE_ENDPOINT,
        RENOVATE_GIT_AUTHOR,
        RENOVATE_USERNAME,
        RENOVATE_TOKEN,
        RENOVATE_GIT_PRIVATE_KEY,
      ]
    environment:
      RENOVATE_CONFIG_FILE: /tmp/config.json
      RENOVATE_PLATFORM: gitea
    commands:
      - |
        echo '{
          "repositories": ["joshuachp/nixos-config"],
          "extends":["config:recommended"],
          "dependencyDashboard": true
        }' > /tmp/config.json
      - renovate
