# Run renovate on push to main
when:
  branch: main
  event:
    - push
    - manual
skip_clone: true
steps:
  - name: renovate
    image: renovate/renovate:39.62.0@sha256:dcc314f63570ddb2bcfb0555ab70272594a890f9dada6ac8a1a16bf3975d5aa5
    # TODO: Add when non root containers work in woodpacker
    # volumes:
    #   - renovate-ci-pvc:/renovate-cache
    secrets:
      [
        GITHUB_COM_TOKEN,
        RENOVATE_ENDPOINT,
        RENOVATE_GIT_AUTHOR,
        RENOVATE_USERNAME,
        RENOVATE_TOKEN,
        RENOVATE_GIT_PRIVATE_KEY,
      ]
    environment:
      RENOVATE_CONFIG_FILE: /tmp/config.json
      # RENOVATE_CACHE_DIR: /renovate-cache
      RENOVATE_PLATFORM: gitea
    backend_options:
      kubernetes:
        securityContext:
          runAsUser: 0
          runAsGroup: 0
          fsGroup: 0
          privileged: true
    commands:
      - |
        printf '{
          "repositories": ["%s"],
          "extends":["config:recommended"],
          "dependencyDashboard": true
        }' "$CI_REPO" > /tmp/config.json
      - renovate
