apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: ""
  #settings.yaml: |
  #  providers:
  #    longhorn:
  #      url: https://longhorn.my.network
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/
  services.yaml: |
    - Dev:
        - Git:
            href: http://git.k.joshuachp.dev/
            icon: forgejo.png
            description: Forgejo
            widget:
              type: gitea
              url: https://git.k.joshuachp.dev
              key: {{HOMEPAGE_VAR_FORGEJO_TOKEN}}
        - Woodpecker:
            href: http://ci.k.joshuachp.dev/
            icon: woodpecker-ci-light.png
            description: Woodpecker Ci
        - ArgoCD:
            href: http://argocd.k.joshuachp.dev/
            icon: argocd.png
            description: ArgoCD
    - Services:
        - Syncthing:
            href: http://syncthing.k.joshuachp.dev/
            icon: syncthing.png
            description: Syncthing web UI
        - Ntfy:
            href: http://ntfy.k.joshuachp.dev/
            icon: ntfy.png
            description: Ntfy web UI
    - Observability:
        - Grafana:
            href: http://grafana.k.joshuachp.dev/
            icon: grafana.png
            description: Grafana
        - Prometheus:
            href: http://prometheus.k.joshuachp.dev/
            icon: prometheus.png
            description: Prometheus
        - AlertManager:
            href: http://alertmanager.k.joshuachp.dev/
            icon: alertmanager.png
            description: AlertManager
    - Infrastructure:
        - Minio:
            href: http://minio-console.k.joshuachp.dev/
            icon: minio-light.png
            description: Minio Console
        - Traefik:
            href: http://traefik.k.joshuachp.dev/
            icon: traefik.png
            description: Traefik dashboard
            widget:
              type: traefik
              url: https://traefik.k.joshuachp.dev
  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
    - search:
        provider: duckduckgo
        target: _blank
  docker.yaml: ""
