apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: ""
  #settings.yaml: |
  #  providers:
  #    longhorn:
  #      url: https://longhorn.my.network
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/
  services.yaml: |
    - Kube services:
        - Git:
            href: http://git.k.joshuachp.dev/
            icon: gitea.png
            description: Gitea instance
        - Syncthing:
            href: http://syncthing.k.joshuachp.dev/
            icon: syncthing.png
            description: Syncthing web UI
        - Traefik:
            href: http://traefik.k.joshuachp.dev/
            icon: traefik.png
            description: Traefik dashboard
        - Kubernetes Dashboard:
            href: http://kubernetes-dashboard.k.joshuachp.dev/
            icon: kubernetes-dashboard.png
            description: Kubernetes dashboard
  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
    - search:
        provider: duckduckgo
        target: _blank
  docker.yaml: ""
