apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/joshuachp/nixos-config
      path: infra/argocd
      ref: repo
    - chart: argo-cd
      repoURL: https://argoproj.github.io/argo-helm
      targetRevision: 6.1.0
      helm:
        valueFiles:
          - $repo/infra/argocd/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: atuin
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/joshuachp/nixos-config
      path: infra/atuin
  destination:
    server: https://kubernetes.default.svc
    namespace: atuin
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/joshuachp/nixos-config
      path: infra/cert-manager
      ref: repo
    - chart: cert-manager
      repoURL: https://charts.jetstack.io
      targetRevision: 1.14.2
      helm:
        valueFiles:
          - $repo/infra/cert-manager/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: firefly
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/joshuachp/nixos-config
      path: infra/firefly
      ref: repo
    - chart: firefly-iii
      repoURL: https://firefly-iii.github.io/kubernetes
      targetRevision: 1.8.0
      helm:
        valueFiles:
          - $repo/infra/firefly/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: firefly
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: forgejo
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/joshuachp/nixos-config
      path: infra/forgejo
      ref: repo
    - chart: forgejo
      repoURL: codeberg.org/forgejo-contrib
      targetRevision: 4.0.1
      helm:
        valueFiles:
          - $repo/infra/forgejo/values.yaml
    - chart: redis
      repoURL: https://charts.bitnami.com/bitnami
      targetRevision: 18.17.0
      helm:
        valueFiles:
          - $repo/infra/forgejo/redis-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: forgejo
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/joshuachp/nixos-config
      path: infra/grafana
      ref: repo
    - chart: grafana
      repoURL: https://grafana.github.io/helm-charts
      targetRevision: 7.3.3
      helm:
        valueFiles:
          - $repo/infra/grafana/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: grafana
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homepage
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/joshuachp/nixos-config
    path: infra/homepage
  destination:
    server: https://kubernetes.default.svc
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/joshuachp/nixos-config
      path: infra/metallb
      ref: repo
    - chart: metallb
      repoURL: https://metallb.github.io/metallb
      targetRevision: 0.14.3
      helm:
        valueFiles:
          - $repo/infra/metallb/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb
  ignoreDifferences:
    - group: "apiextensions.k8s.io"
      kind: CustomResourceDefinition
      name: bgppeers.metallb.io
      jsonPointers:
        - /spec/conversion/webhook/clientConfig/caBundle
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ntfy
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/joshuachp/nixos-config
    path: infra/ntfy
  destination:
    server: https://kubernetes.default.svc
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/joshuachp/nixos-config
    path: infra/postgres
  destination:
    server: https://kubernetes.default.svc
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/joshuachp/nixos-config
      path: infra/prometheus
      ref: repo
    - chart: prometheus
      repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: 25.15.0
      helm:
        valueFiles:
          - $repo/infra/prometheus/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: prometheus
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: syncthing
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/joshuachp/nixos-config
    path: infra/syncthing
  destination:
    server: https://kubernetes.default.svc
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/joshuachp/nixos-config
      path: infra/traefik
      ref: repo
    - chart: traefik
      repoURL: https://traefik.github.io/charts
      targetRevision: 26.0.0
      helm:
        valueFiles:
          - $repo/infra/traefik/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
