apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated: {}
  sources:
    - repoURL: https://github.com/joshuachp/nixos-config
      path: infra/argocd
      ref: repo
    - chart: argo-cd
      repoURL: https://argoproj.github.io/argo-helm
      targetRevision: 7.8.7
      helm:
        valueFiles:
          - $repo/infra/argocd/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: atuin
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated: {}
  sources:
    - repoURL: https://github.com/joshuachp/nixos-config
      path: infra/atuin
  destination:
    server: https://kubernetes.default.svc
    namespace: atuin
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated: {}
  sources:
    - repoURL: https://github.com/joshuachp/nixos-config
      path: infra/cert-manager
      ref: repo
    - chart: cert-manager
      repoURL: https://charts.jetstack.io
      targetRevision: v1.17.1
      helm:
        valueFiles:
          - $repo/infra/cert-manager/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coredns
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated: {}
  sources:
    - repoURL: https://github.com/joshuachp/nixos-config
      path: infra/coredns
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: forgejo
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated: {}
  sources:
    - repoURL: https://github.com/joshuachp/nixos-config
      path: infra/forgejo
      ref: repo
    - chart: forgejo
      repoURL: code.forgejo.org/forgejo-helm
      targetRevision: 11.0.3
      helm:
        valueFiles:
          - $repo/infra/forgejo/values.yaml
    - chart: redis
      repoURL: "registry-1.docker.io/bitnamicharts"
      targetRevision: 20.11.0
      helm:
        valueFiles:
          - $repo/infra/forgejo/redis-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: forgejo
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homepage
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated: {}
  source:
    repoURL: https://github.com/joshuachp/nixos-config
    path: infra/homepage
  destination:
    server: https://kubernetes.default.svc
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated: {}
  sources:
    - repoURL: https://github.com/joshuachp/nixos-config
      path: infra/ingress-nginx
      ref: repo
    - chart: ingress-nginx
      repoURL: https://kubernetes.github.io/ingress-nginx
      targetRevision: 4.12.0
      helm:
        valueFiles:
          - $repo/infra/ingress-nginx/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated: {}
  sources:
    - repoURL: https://github.com/joshuachp/nixos-config
      path: infra/metallb
      ref: repo
    - chart: metallb
      repoURL: https://metallb.github.io/metallb
      targetRevision: 0.14.9
      helm:
        valueFiles:
          - $repo/infra/metallb/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb
  ignoreDifferences:
    - group: "apiextensions.k8s.io"
      kind: CustomResourceDefinition
      name: bgppeers.metallb.io
      jsonPointers:
        - /spec/conversion/webhook/clientConfig/caBundle
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: miniflux
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated: {}
  source:
    repoURL: https://github.com/joshuachp/nixos-config
    path: infra/miniflux
  destination:
    server: https://kubernetes.default.svc
    namespace: miniflux
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated: {}
  source:
    repoURL: https://github.com/joshuachp/nixos-config
    path: infra/minio
  destination:
    server: https://kubernetes.default.svc
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextcloud
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated: {}
  sources:
    - repoURL: https://github.com/joshuachp/nixos-config
      path: infra/nextcloud
      ref: repo
    - chart: nextcloud
      repoURL: https://nextcloud.github.io/helm/
      targetRevision: 6.6.6
      helm:
        valueFiles:
          - $repo/infra/nextcloud/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: nextcloud
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ntfy
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated: {}
  source:
    repoURL: https://github.com/joshuachp/nixos-config
    path: infra/ntfy
  destination:
    server: https://kubernetes.default.svc
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated: {}
    syncOptions:
      - ServerSideApply=true
  sources:
    - repoURL: https://github.com/joshuachp/nixos-config
      path: infra/observability
      ref: repo
    - chart: kube-prometheus-stack
      repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: 69.7.2
      helm:
        valueFiles:
          - $repo/infra/observability/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pi-hole
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated: {}
  source:
    repoURL: https://github.com/joshuachp/nixos-config
    path: infra/pi-hole
  destination:
    server: https://kubernetes.default.svc
    namespace: pi-hole
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/joshuachp/nixos-config
    path: infra/postgres
  destination:
    server: https://kubernetes.default.svc
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: renovate
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated: {}
  source:
    repoURL: https://github.com/joshuachp/nixos-config
    path: infra/renovate
  destination:
    server: https://kubernetes.default.svc
    namespace: renovate
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: syncthing
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated: {}
  source:
    repoURL: https://github.com/joshuachp/nixos-config
    path: infra/syncthing
  destination:
    server: https://kubernetes.default.svc
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: woodpecker
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated: {}
  sources:
    - repoURL: https://github.com/joshuachp/nixos-config
      path: infra/woodpecker
      ref: repo
    - chart: woodpecker
      repoURL: https://woodpecker-ci.org/
      targetRevision: 3.0.5
      helm:
        valueFiles:
          - $repo/infra/woodpecker/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: woodpecker
