apiVersion: v1
kind: Secret
metadata:
  name: forgejo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: forgejo
  enableOCI: "true"
  type: helm
  url: code.forgejo.org/forgejo-helm
---
apiVersion: v1
kind: Secret
metadata:
  name: bitnami
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: bitnami
  enableOCI: "true"
  type: helm
  url: registry-1.docker.io/bitnamicharts
---
apiVersion: v1
kind: Secret
metadata:
  name: nixos-config
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: nixos-config
  type: git
  url: https://github.com/joshuachp/nixos-config
