apiVersion: v1
kind: Secret
metadata:
  name: forgejo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: forgejo
  enableOCI: "true"
  type: helm
  url: codeberg.org/forgejo-contrib/
---
apiVersion: v1
kind: Secret
metadata:
  name: bitnami
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: bitnami
  type: helm
  url: https://charts.bitnami.com/bitnami
---
apiVersion: v1
kind: Secret
metadata:
  name: nixos-config
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: nixos-config
  type: git
  url: https://github.com/joshuachp/nixos-config
