name: check
on:
  push:
    branches:
      - main
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
jobs:
  check:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          github-token: ${{ secrets.NIX_REPO }}
      - uses: DeterminateSystems/magic-nix-cache-action@main
        with:
          # Don't send the diagnostics automatically
          diagnostic-endpoint: ""
      - run: nix flake check
